const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const modal=$('#mission-modal'),visual=$('[data-dialog-visual]'),copy=$('[data-mission-step]'),stage=$('#mission-stage'),complete=$('[data-complete-view]'),reaction=$('#mission-reaction'),progressLabel=$('#mission-progress-label'),progressBar=$('.mission-progress i'),shareLink=$('#mission-share-link');
const pointsKey='itaso-nna-points-v1',missionsKey='itaso-nna-missions-v1';let key,lastButton,state;
const missions={
 empaques:{title:'Detective de empaques',instruction:'Busca un producto que tengas cerca y mira el frente del empaque.',art:'assets/naranja-detective-mision.svg',artSize:'72%',soft:'#FFE9DF',accent:'#F56A28'},
 grupos:{title:'Busca los grupos',instruction:'Mira una comida o algunos alimentos que tengas cerca.',art:'assets/recurso2.PNG',artSize:'76%',soft:'#E4F9EA',accent:'#00A53D'},
 agua:{title:'Agua a la mano',instruction:'Busca una forma de tener agua simple cerca durante tu día.',detail:'Puede ser llenar una botella, servir un vaso o dejar una jarra en un lugar fácil de encontrar.',art:'assets/bebidas/agua.svg',artSize:'42%',soft:'#E4F6FD',accent:'#00B3F0'},
 alrededor:{title:'Mira a tu alrededor',instruction:'Busca una forma de moverte que puedas hacer hoy.',art:'assets/tomate-ejercicio-mision.svg',artSize:'72%',soft:'#FFE8EC',accent:'#DC2839'}
};
const seals=['Exceso de calorías','Exceso de azúcares','Exceso de grasas saturadas','Exceso de grasas trans','Exceso de sodio','Vi otro aviso'];
const waterActions=[['Llené una botella','una botella'],['Serví un vaso','un vaso'],['Dejé una jarra cerca','una jarra'],['Hice otra cosa','other']],waterPlaces=[['En mi cuarto','mi cuarto'],['En la cocina','la cocina'],['En mi mochila','mi mochila'],['En la mesa','la mesa'],['En otro lugar','other']],waterMoments=[['Mientras juego','mientras juego'],['Cuando estudio','cuando estudio'],['Cuando salgo','cuando salgo'],['Durante una comida','durante una comida'],['Después de moverme','después de moverme'],['En otro momento','other']];
function esc(v){return String(v||'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
const steps=()=>key==='empaques'?(state.a.found==='no'?['intro','found','product','summary']:['intro','found','product','seals','summary']):key==='grupos'?['intro','foods','variety','summary']:key==='agua'?['intro','waterAction','waterPlace','waterMoment','summary']:['intro','moveAction','moveTime','summary'];
const buttons=(label='Continuar',disabled=false)=>`<div class="mission-dialog-actions"><button class="button button-primary mission-next" ${disabled?'disabled':''}>${label}</button><button class="mission-back mission-prev">${state.i?'Atrás':'Volver a Misiones'}</button></div>`;
const choices=(label,items,selected)=>`<div class="mission-choices" role="group" aria-label="${label}">${items.map(([t,v])=>`<button class="mission-choice ${selected===v?'is-selected':''}" data-value="${v}" aria-pressed="${selected===v}">${t}</button>`).join('')}</div>`;
const field=(label,placeholder,value='',answer='')=>`<label class="mission-field"><span>${label}</span><input maxlength="80" value="${esc(value)}" placeholder="${placeholder}" data-answer="${answer}"></label>`;
const other=(step,answer,label)=>state.a[step]==='other'?field(label,'Una respuesta corta',state.a[answer],answer):'';
const text=(name,otherName)=>state.a[name]==='other'?(state.a[otherName]||'otra opción'):(state.a[name]||'');
function result(){const a=state.a;if(key==='empaques'){const yes=a.found==='yes',learning=yes?'Los sellos están al frente para que puedas encontrarlos rápidamente.':'No todos los empaques tienen sellos, pero todavía puedes encontrar información en otras partes.';return{observed:a.product,found:yes?`Encontré: ${(a.seals||[]).join(', ')}.`:'No encontré sellos.',learning,summary:`Miré ${a.product}.`}}if(key==='grupos')return{observed:a.foods,found:a.variety==='yes'?'Sí, encontré más de un grupo.':a.variety==='no'?'No encontré más de un grupo.':'No estoy seguro de cuántos grupos encontré.',learning:'Una comida puede juntar alimentos de distintos grupos.',summary:`Vi: ${a.foods}.`};if(key==='agua'){const action=text('waterAction','waterActionOther'),place=text('waterPlace','waterPlaceOther'),moment=text('waterMoment','waterMomentOther');return{observed:`Preparé: ${action}.`,found:`La dejé en ${place}. Pensé que puede servirme ${moment}.`,learning:'Tener agua a la mano hace más fácil acordarte de tomarla durante el día.',summary:`Dejaste ${action} en ${place} para tener agua cerca ${moment}.`}}return{observed:`Elegí: ${text('moveAction','moveActionOther')}.`,found:`Podría hacerlo: ${a.moveTime}.`,learning:'Hay muchas formas de moverte durante el día.',summary:`Encontraste una forma de moverte: ${text('moveAction','moveActionOther')}.`}}
function render(){const m=missions[key],s=steps()[state.i],a=state.a,all=steps(),shown=Math.max(0,state.i),total=all.length-1;progressLabel.textContent=s==='intro'?'ANTES DE EMPEZAR':s==='summary'?'RESUMEN':`PASO ${shown} DE ${total-1}`;progressBar.style.setProperty('--progress',`${(state.i+1)/all.length*100}%`);
 if(s==='intro')stage.innerHTML=`<p class="eyebrow">ACTIVIDAD</p><h2>${m.title}</h2><div class="mission-info-block"><strong>¿Qué harás?</strong><p>${m.instruction}</p>${m.detail?`<p>${m.detail}</p>`:''}</div>${buttons(key==='agua'?'Empezar misión':'Empezar')}`;
 if(s==='found')stage.innerHTML=`<p class="eyebrow">LO QUE OBSERVÉ</p><h2>¿Encontraste algún sello?</h2>${choices('Sellos',[['Sí','yes'],['No','no']],a.found)}${buttons('Continuar',!a.found)}`;
 if(s==='product')stage.innerHTML=`<p class="eyebrow">CUÉNTANOS</p><h2>¿Qué producto observaste?</h2>${field('Escribe una respuesta corta','Por ejemplo: una bebida, cereal…',a.product,'product')}${buttons('Continuar',!String(a.product||'').trim())}`;
 if(s==='seals')stage.innerHTML=`<p class="eyebrow">CUÉNTANOS</p><h2>¿Qué sello viste?</h2><p class="mission-stage-copy">Puedes elegir más de uno.</p><div class="mission-chips">${seals.map(t=>`<button class="mission-chip ${(a.seals||[]).includes(t)?'is-selected':''}">${t}</button>`).join('')}</div>${buttons('Continuar',!(a.seals||[]).length)}`;
 if(s==='foods')stage.innerHTML=`<p class="eyebrow">LO QUE OBSERVÉ</p><h2>¿Qué alimentos viste?</h2>${field('Escribe algunos alimentos','Por ejemplo: tortilla, frijoles…',a.foods,'foods')}${buttons('Continuar',!String(a.foods||'').trim())}`;
 if(s==='variety')stage.innerHTML=`<p class="eyebrow">CUÉNTANOS</p><h2>¿Encontraste alimentos de más de un grupo?</h2>${choices('Grupos',[['Sí','yes'],['No','no'],['No estoy seguro','unsure']],a.variety)}${buttons('Continuar',!a.variety)}`;
 if(s==='waterAction')stage.innerHTML=`<p class="eyebrow">PASO 1</p><h2>¿Qué hiciste?</h2>${choices('Acción',waterActions,a.waterAction)}${other('waterAction','waterActionOther','Cuéntanos qué hiciste')}${buttons('Continuar',!a.waterAction||(a.waterAction==='other'&&!String(a.waterActionOther||'').trim()))}`;
 if(s==='waterPlace')stage.innerHTML=`<p class="eyebrow">PASO 2</p><h2>¿Dónde la dejaste?</h2>${choices('Lugar',waterPlaces,a.waterPlace)}${other('waterPlace','waterPlaceOther','¿En qué lugar?')}${buttons('Continuar',!a.waterPlace||(a.waterPlace==='other'&&!String(a.waterPlaceOther||'').trim()))}`;
 if(s==='waterMoment')stage.innerHTML=`<p class="eyebrow">PASO 3</p><h2>¿Cuándo podría servirte tenerla cerca?</h2>${choices('Momento',waterMoments,a.waterMoment)}${other('waterMoment','waterMomentOther','¿En qué momento?')}${buttons('Continuar',!a.waterMoment||(a.waterMoment==='other'&&!String(a.waterMomentOther||'').trim()))}`;
 if(s==='moveAction')stage.innerHTML=`<p class="eyebrow">OBSERVA</p><h2>¿Cómo podrías moverte hoy?</h2>${choices('Movimiento',[['Caminar','caminar'],['Bailar','bailar'],['Jugar','jugar'],['Andar en bicicleta','andar en bicicleta'],['Otra forma','other']],a.moveAction)}${other('moveAction','moveActionOther','¿Qué forma encontraste?')}${buttons('Continuar',!a.moveAction||(a.moveAction==='other'&&!String(a.moveActionOther||'').trim()))}`;
 if(s==='moveTime')stage.innerHTML=`<p class="eyebrow">EN TU DÍA</p><h2>¿En qué momento podrías hacerlo?</h2>${field('Escribe una respuesta corta','Por ejemplo: al salir…',a.moveTime,'moveTime')}${buttons('Continuar',!String(a.moveTime||'').trim())}`;
 if(s==='summary'){const r=result();stage.innerHTML=`<p class="eyebrow">LO QUE DESCUBRISTE</p><h2>${m.title}</h2><div class="mission-summary"><p>${esc(r.summary)}</p>${key==='agua'?'':`<p>${esc(r.found)}</p>`}<strong>${r.learning}</strong></div>${buttons('Completar misión')}`}bind(s);stage.focus()}
function bind(s){stage.querySelectorAll('.mission-choice').forEach(b=>b.onclick=()=>{state.a[s]=b.dataset.value;render()});stage.querySelectorAll('.mission-chip').forEach(b=>b.onclick=()=>{const set=new Set(state.a.seals||[]);set.has(b.textContent)?set.delete(b.textContent):set.add(b.textContent);state.a.seals=[...set];render()});stage.querySelectorAll('input').forEach(i=>i.oninput=()=>{state.a[i.dataset.answer]=i.value;stage.querySelector('.mission-next').disabled=!i.value.trim()});stage.querySelector('.mission-prev').onclick=()=>{if(!state.i)return closeMission();state.i--;render()};stage.querySelector('.mission-next').onclick=()=>{if(s==='summary')return finish();state.i++;render()}}
function openMission(k,b){key=k;lastButton=b;state={i:0,a:{seals:[]}};const m=missions[k];modal.classList.remove('is-complete');visual.dataset.mission=k;visual.style.backgroundColor=m.soft;visual.style.setProperty('--dialog-art',`url("${m.art}")`);visual.style.setProperty('--dialog-art-size',m.artSize||'68%');modal.style.setProperty('--mission-soft',m.soft);modal.style.setProperty('--mission-accent',m.accent);copy.hidden=false;visual.hidden=false;complete.hidden=true;modal.hidden=false;document.body.classList.add('mission-open');render();stage.querySelector('button,input')?.focus()}
function closeMission(){modal.hidden=true;modal.classList.remove('is-complete');document.body.classList.remove('mission-open');lastButton?.focus()}
function finish(){const r=result();try{const saved=JSON.parse(localStorage.getItem(missionsKey))||{};saved[key]={key,title:missions[key].title,...r,completedAt:new Date().toISOString()};localStorage.setItem(missionsKey,JSON.stringify(saved));const pts=JSON.parse(localStorage.getItem(pointsKey))||{total:0,events:{}};pts.events||={};if(!pts.events[`mision-${key}-completa`]){pts.events[`mision-${key}-completa`]=10;pts.total=Number(pts.total||0)+10;localStorage.setItem(pointsKey,JSON.stringify(pts))}}catch(_){}reaction.textContent=key==='agua'?'Encontraste una forma de tener agua cerca en un momento de tu día.':`${r.learning} Observaste y contaste lo que encontraste.`;shareLink.href=`index.html?page=compartir&mission=${key}`;copy.hidden=true;visual.hidden=true;complete.hidden=false;modal.classList.add('is-complete');shareLink.focus()}
$$('[data-mission]').forEach(b=>b.onclick=()=>openMission(b.dataset.mission,b));$$('[data-close-mission]').forEach(b=>b.onclick=closeMission);modal.onclick=e=>{if(e.target===modal)closeMission()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeMission()});
const header=$('[data-header]'),nav=$('#main-nav'),toggle=$('.menu-toggle');toggle.onclick=()=>{const o=!nav.classList.contains('is-open');nav.classList.toggle('is-open',o);toggle.setAttribute('aria-expanded',o)};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('is-open'));window.addEventListener('scroll',()=>header.classList.toggle('is-scrolled',scrollY>18),{passive:true});$('[data-caregiver-link]').onclick=e=>{e.preventDefault();};
const reveals=$$('.mission-reveal');if('IntersectionObserver'in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');o.unobserve(e.target)}}),{threshold:.12});reveals.forEach(x=>o.observe(x))}else reveals.forEach(x=>x.classList.add('is-visible'));
