const drinks = window.ITASO_MEMORAMA_DRINKS || [];
const board = document.querySelector('#memory-board');
const learning = document.querySelector('#memory-learning');
const finish = document.querySelector('#memory-finish');
const pairsLabel = document.querySelector('#memory-pairs');
const memoryShell = document.querySelector('.memory-shell');
const intro = document.querySelector('#memory-intro');
const POINTS_KEY='itaso-nna-points-v1';
let first=null, second=null, locked=false, matched=new Set(), pendingFinish=false;

function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function deck(){return shuffle(drinks.flatMap((drink)=>[1,2].map((copy)=>({...drink,cardId:`${drink.id}-${copy}`}))));}
function clearTurn(){first=null;second=null;locked=false;}
function updateStatus(){pairsLabel.textContent=`${matched.size} de ${drinks.length} parejas`;}
function start(){first=null;second=null;locked=false;matched=new Set();pendingFinish=false;learning.hidden=true;finish.hidden=true;board.replaceChildren();deck().forEach((card,index)=>board.append(createCard(card,index)));updateStatus();}
function beginGame(){intro.hidden=true;board.hidden=false;memoryShell.classList.remove('is-intro');document.querySelector('#memory-heading-title').textContent='Encuentra las 15 parejas';start();board.querySelector('.memory-card')?.focus();}
function createCard(card,index){const button=document.createElement('button');button.type='button';button.className='memory-card';button.dataset.drinkId=card.id;button.setAttribute('aria-label',`Carta ${index+1}, boca abajo`);button.innerHTML=`<span class="memory-card-inner"><span class="memory-card-face memory-card-back"><img src="../assets/memorama/tarjetamemorama.svg" alt=""></span><span class="memory-card-face memory-card-front"><img src="${card.image}" alt=""></span></span>`;button.addEventListener('click',()=>flip(button,card,index));return button;}
function flip(button,card,index){if(locked||button.classList.contains('is-flipped')||button.classList.contains('is-matched'))return;button.classList.add('is-flipped');button.setAttribute('aria-label',`${card.name}, carta volteada`);if(!first){first={button,card,index};return;}second={button,card,index};locked=true;if(first.card.id===second.card.id){first.button.classList.add('is-matched');second.button.classList.add('is-matched');matched.add(card.id);pendingFinish=matched.size===drinks.length;updateStatus();setTimeout(()=>showLearning(card),430);}else{setTimeout(()=>{[first,second].forEach((item)=>{item.button.classList.remove('is-flipped');item.button.setAttribute('aria-label',`Carta ${item.index+1}, boca abajo`);});clearTurn();},700);}}
const sealAssets={'Exceso de Calorías':'../assets/sellosadvertencia/calorias.svg','Exceso de Azúcares':'../assets/sellosadvertencia/azucares.svg','Exceso de Grasas Saturadas':'../assets/sellosadvertencia/grasas-saturadas.svg','Exceso de Grasas Trans':'../assets/sellosadvertencia/grasas-trans.svg','Exceso de Sodio':'../assets/sellosadvertencia/sodio.svg'};
const warningAssets={'Contiene edulcorantes, no recomendable en niños':'../assets/sellosadvertencia/edulcorantes.svg','Contiene cafeína, evitar en niños':'../assets/sellosadvertencia/cafeina.svg'};
function seal(text){const item=document.createElement('img');item.className='warning-seal';item.src=sealAssets[text];item.alt=text;return item;}
function showLearning(drink){document.querySelector('#learning-image').src=drink.image;document.querySelector('#learning-image').alt=drink.name;document.querySelector('#learning-name').textContent=drink.name;const sealCount=drink.seals.length;const warningCount=drink.warnings.length;document.querySelector('#finding-summary').textContent=`${sealCount} ${sealCount===1?'sello':'sellos'} · ${warningCount} ${warningCount===1?'aviso':'avisos'}`;const seals=document.querySelector('#learning-seals');seals.replaceChildren();if(drink.seals.length)drink.seals.forEach((text)=>seals.append(seal(text)));else{const item=document.createElement('span');item.className='no-seals';item.textContent='Sin sellos';seals.append(item);}const warnings=document.querySelector('#learning-warnings');warnings.replaceChildren();drink.warnings.forEach((text)=>{const item=document.createElement('img');item.className='warning-chip';item.src=warningAssets[text];item.alt=text;warnings.append(item);});const meaning=document.querySelector('#learning-meaning');meaning.replaceChildren();drink.meaning.forEach((text)=>{const p=document.createElement('p');p.textContent=text;meaning.append(p);});document.querySelector('#learning-clue').textContent=drink.clue;learning.hidden=false;document.querySelector('#continue-memory').focus();}
function award(){try{const saved=JSON.parse(localStorage.getItem(POINTS_KEY))||{total:0,events:{}};saved.events||={};if(!saved.events['juego-memorama-completo']){saved.events['juego-memorama-completo']=20;saved.total=Number(saved.total||0)+20;localStorage.setItem(POINTS_KEY,JSON.stringify(saved));}}catch(_){}}
document.querySelector('#continue-memory').addEventListener('click',()=>{learning.hidden=true;clearTurn();if(pendingFinish){award();finish.hidden=false;document.querySelector('#play-memory-again').focus();}else board.querySelector('.memory-card:not(.is-matched)')?.focus();});
document.querySelector('#start-memory').addEventListener('click',beginGame);document.querySelector('#restart-memory').addEventListener('click',start);document.querySelector('#play-memory-again').addEventListener('click',start);
const navigation=document.querySelector('#main-nav');const toggle=document.querySelector('.menu-toggle');toggle.addEventListener('click',()=>{const open=!navigation.classList.contains('is-open');navigation.classList.toggle('is-open',open);toggle.setAttribute('aria-expanded',String(open));});
const notice=document.querySelector('.notice');document.querySelector('[data-caregiver-link]').addEventListener('click',(event)=>{event.preventDefault();notice.textContent='El acceso para cuidadores se conectará en la siguiente etapa.';notice.hidden=false;setTimeout(()=>notice.hidden=true,3000);});
function renderIntroCharacter(){const box=document.querySelector('.memory-intro-character');const body=document.querySelector('.memory-intro-body');const face=document.querySelector('.memory-intro-face');if(!box||!body||!face)return;const assets={tomate:['../assets/tomate-1.svg','../assets/tomate-2.svg','../assets/tomate-3.svg'],zanahoria:['../assets/zanahoria-1.svg','../assets/zanahoria-2.svg','../assets/zanahoria-3.svg'],naranja:['../assets/naranja-1.svg','../assets/naranja-2.svg','../assets/naranja-3.svg'],berenjena:['../assets/berenjena-1.svg','../assets/berenjena-2.svg','../assets/berenjena-3.svg'],fresa:['../assets/fresa-1.svg','../assets/fresa-2.svg','../assets/fresa-3.svg']};box.dataset.fruit='tomate';box.dataset.shape='intro';const settings={tomate:[[52,32],[51,25],[50,27]],zanahoria:[[50,25],[58,23],[68,22]],naranja:[[50,29],[51,27],[50,26]],berenjena:[[51,27],[54,33],[52,24]],fresa:[[53,28],[54,27],[55,27]]};try{const character=JSON.parse(localStorage.getItem('itasoRedesignCharacterV2'));const asset=assets[character?.fruit]?.[character?.shape];if(!asset)return;box.dataset.fruit=character.fruit;box.dataset.shape=String(character.shape);body.src=asset;body.alt=character.name?`Personaje de ${character.name}`:'Tu personaje de ITASO';if(character.expression){const [top,width]=settings[character.fruit][character.shape];face.src=character.expression==='recompensa'?'../assets/recompensa-nueva-expresion.svg':`../assets/expressions-svg/expression-${character.expression}.png`;face.style.top=`${top}%`;face.style.width=`${width}%`;face.hidden=false;}}catch(_){}}
renderIntroCharacter();
